# Generated by Django 5.0.6 on 2025-03-16 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100, unique=True)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('route_number', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'bus route',
                'verbose_name_plural': 'bus routes',
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('sequence_number', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.busroute')),
            ],
            options={
                'verbose_name': 'bus stop',
                'verbose_name_plural': 'bus stops',
                'ordering': ['route', 'sequence_number'],
                'unique_together': {('route', 'sequence_number')},
            },
        ),
        migrations.CreateModel(
            name='BusPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='buspass_photos/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_rejected', models.DateTimeField(blank=True, null=True)),
                ('profession', models.CharField(choices=[('student', 'Student'), ('senior_citizen', 'Senior Citizen'), ('general', 'General'), ('government_employee', 'Government Employee')], default='general', max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('pass_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buspasses', to=settings.AUTH_USER_MODEL)),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='home.busroute')),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_from', to='home.busstop')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_to', to='home.busstop')),
            ],
            options={
                'verbose_name': 'bus pass',
                'verbose_name_plural': 'bus passes',
            },
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=10)),
                ('end_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_segments', to='home.busstop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.busroute')),
                ('start_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_segments', to='home.busstop')),
            ],
            options={
                'verbose_name': 'route segment',
                'verbose_name_plural': 'route segments',
            },
        ),
    ]
