# Generated by Django 5.0.6 on 2025-03-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_busroute_busstop_buspass_routesegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspass',
            name='pass_validity_in_days',
            field=models.BigIntegerField(default=30),
        ),
    ]
