# Generated by Django 5.0.6 on 2025-03-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_buspass_pass_validity_in_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspass',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
