# Generated by Django 5.0.6 on 2025-03-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_buspass_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspass',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
